language: python
sudo: false
python:
  - "3.5"
  - "3.6"

# Checks that requirements.txt is up to date
install:
  - pip install -r requirements.txt

# Checks for syntax errors
script:
  - python -m py_compile run-bot.py
