language: python
sudo: false
python:
  - "3.5"
  - "3.6"

# Checks that Pipfile is up to date
install:
  - pip install pipenv
  - pipenv install --dev

# Lints
script:
  - python -m py_compile jb-bot.py
  - python -m compileall commands/
  - pycodestyle --ignore=E501 jb-bot.py
  - pycodestyle --ignore=E501,E402 -r commands/

notifications:
  email: false
